-- Split Scan: database schema for Supabase (PostgreSQL).
-- Paste into Supabase → SQL Editor → New query → Run. Then run seed.sql.
-- Running it again DROPS every table and starts fresh.
--
-- Table and column names follow our ERD (docs/ioya-erd.pdf), written in Postgres snake_case:
-- Users.UserFirstName → users.user_first_name, Contacts_Payment_Method → contacts_payment_method, etc.
-- Money is stored as whole cents (1959 = $19.59).

DROP TABLE IF EXISTS item_assignments, participants, line_items, receipts, events,
  contacts_payment_method, payment_methods, group_members, friend_groups, contacts, users CASCADE;

CREATE TABLE users (
  user_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_first_name  text NOT NULL,
  user_last_name   text NOT NULL,
  phone            text
);

-- Each user also has one contact row for themselves (same name and phone),
-- so the payer can be a participant and be assigned items like everyone else.
CREATE TABLE contacts (
  contact_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cont_first_name  text NOT NULL,
  cont_last_name   text NOT NULL DEFAULT '',
  phone            text,
  user_id          integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE friend_groups (
  group_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name  text NOT NULL
);

CREATE TABLE group_members (
  group_id    integer NOT NULL REFERENCES friend_groups(group_id) ON DELETE CASCADE,
  contact_id  integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, contact_id)
);

CREATE TABLE payment_methods (
  pay_method_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pay_method_name  text NOT NULL UNIQUE
);

CREATE TABLE contacts_payment_method (
  contact_id           integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  pay_method_id        integer NOT NULL REFERENCES payment_methods(pay_method_id),
  pay_method_username  text NOT NULL,
  is_preferred         boolean NOT NULL DEFAULT false,
  PRIMARY KEY (contact_id, pay_method_id)
);
-- At most one preferred payment method per contact.
CREATE UNIQUE INDEX one_preferred_method_per_contact ON contacts_payment_method (contact_id) WHERE is_preferred;

CREATE TABLE events (
  event_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name  text NOT NULL
);

CREATE TABLE receipts (
  receipt_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id        integer NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  payer_user_id   integer NOT NULL REFERENCES users(user_id),
  merchant_name   text NOT NULL,
  receipt_date    date NOT NULL DEFAULT current_date,
  tax_cents       integer NOT NULL DEFAULT 0 CHECK (tax_cents >= 0),
  fees_cents      integer NOT NULL DEFAULT 0 CHECK (fees_cents >= 0),
  tip_percent     numeric(5,2) NOT NULL DEFAULT 0 CHECK (tip_percent >= 0),
  tip_cents       integer NOT NULL DEFAULT 0 CHECK (tip_cents >= 0),
  total_cents     integer NOT NULL CHECK (total_cents >= 0)  -- total printed on the receipt (items + tax + fees, before tip)
);

CREATE TABLE line_items (
  item_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id   integer NOT NULL REFERENCES receipts(receipt_id) ON DELETE CASCADE,
  description  text NOT NULL,
  price_cents  integer NOT NULL CHECK (price_cents >= 0),
  position     integer NOT NULL
);

-- paid_method_id is empty until the person pays you back; then it records how they paid.
CREATE TABLE participants (
  contact_id      integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  event_id        integer NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  paid_method_id  integer REFERENCES payment_methods(pay_method_id),
  PRIMARY KEY (contact_id, event_id)
);

CREATE TABLE item_assignments (
  contact_id   integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  item_id      integer NOT NULL REFERENCES line_items(item_id) ON DELETE CASCADE,
  share_cents  integer NOT NULL CHECK (share_cents >= 0),
  PRIMARY KEY (contact_id, item_id)
);

-- Row Level Security. The app has no login yet and uses Supabase's public "anon" key,
-- so: anyone with the key can READ every table, can UPDATE only participants.paid_method_id
-- (the "Mark as paid" button), and can add/edit/delete contacts only through the save_contact and
-- delete_contact functions at the bottom of this file. Every other change is made in the Supabase dashboard.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','contacts','friend_groups','group_members','payment_methods',
    'contacts_payment_method','events','receipts','line_items','participants','item_assignments']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY "Public read" ON %I FOR SELECT TO anon USING (true)', t);
  END LOOP;
END $$;

CREATE POLICY "Public can mark paid" ON participants FOR UPDATE TO anon USING (true) WITH CHECK (true);
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM anon;
GRANT UPDATE (paid_method_id) ON participants TO anon;

-- Contact editing from the app (same as supabase/contacts-sync.sql).
-- Create a contact (p_contact_id = null) or replace an existing one, along with its payment methods.
-- p_methods is a JSON array like: [{"pay_method_id": 1, "username": "@tanner", "preferred": true}]
CREATE OR REPLACE FUNCTION save_contact(
  p_contact_id  integer,
  p_first_name  text,
  p_last_name   text,
  p_phone       text,
  p_methods     jsonb
) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_contact_id integer;
  v_user_id    constant integer := 1;  -- No login yet: every contact belongs to the demo user.
BEGIN
  IF coalesce(trim(p_first_name), '') = '' THEN
    RAISE EXCEPTION 'Add a first name.';
  END IF;
  IF (SELECT count(*) FROM jsonb_array_elements(coalesce(p_methods, '[]')) m
       WHERE coalesce((m->>'preferred')::boolean, false) AND coalesce(trim(m->>'username'), '') <> '') > 1 THEN
    RAISE EXCEPTION 'Pick only one preferred payment method.';
  END IF;

  IF p_contact_id IS NULL THEN
    INSERT INTO contacts (cont_first_name, cont_last_name, phone, user_id)
    VALUES (trim(p_first_name), coalesce(trim(p_last_name), ''), nullif(trim(p_phone), ''), v_user_id)
    RETURNING contact_id INTO v_contact_id;
  ELSE
    UPDATE contacts
       SET cont_first_name = trim(p_first_name),
           cont_last_name  = coalesce(trim(p_last_name), ''),
           phone           = nullif(trim(p_phone), '')
     WHERE contact_id = p_contact_id AND user_id = v_user_id
    RETURNING contact_id INTO v_contact_id;
    IF v_contact_id IS NULL THEN
      RAISE EXCEPTION 'That contact no longer exists.';
    END IF;
    DELETE FROM contacts_payment_method WHERE contact_id = v_contact_id;
  END IF;

  INSERT INTO contacts_payment_method (contact_id, pay_method_id, pay_method_username, is_preferred)
  SELECT v_contact_id, (m->>'pay_method_id')::integer, trim(m->>'username'), coalesce((m->>'preferred')::boolean, false)
    FROM jsonb_array_elements(coalesce(p_methods, '[]')) m
   WHERE coalesce(trim(m->>'username'), '') <> '';

  RETURN v_contact_id;
END $$;

-- Delete a contact, unless they are on a past split (deleting them would erase their
-- items from that receipt) or they are the user's own "You" row.
CREATE OR REPLACE FUNCTION delete_contact(p_contact_id integer)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM participants WHERE contact_id = p_contact_id) THEN
    RAISE EXCEPTION 'This contact is part of a past split, so they can''t be deleted.';
  END IF;
  IF EXISTS (SELECT 1 FROM contacts c JOIN users u ON u.user_id = c.user_id
              WHERE c.contact_id = p_contact_id AND c.cont_first_name = u.user_first_name
                AND c.cont_last_name = u.user_last_name AND c.phone IS NOT DISTINCT FROM u.phone) THEN
    RAISE EXCEPTION 'You can''t delete your own contact.';
  END IF;
  DELETE FROM contacts WHERE contact_id = p_contact_id AND user_id = 1;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'That contact no longer exists.';
  END IF;
END $$;

REVOKE ALL ON FUNCTION save_contact(integer, text, text, text, jsonb), delete_contact(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION save_contact(integer, text, text, text, jsonb), delete_contact(integer) TO anon;
