-- Split Scan: database schema for Supabase (PostgreSQL).
-- Paste into Supabase → SQL Editor → New query → Run. Then run seed.sql.
-- Running it again DROPS every table and starts fresh.
--
-- Table and column names follow our ERD (docs/ioya-erd.pdf), written in Postgres snake_case:
-- Users.UserFirstName → users.user_first_name, Contacts_Payment_Method → contacts_payment_method, etc.
-- Money is stored as whole cents (1959 = $19.59).

DROP TABLE IF EXISTS item_assignments, participants, line_items, receipts, events,
  contacts_payment_method, payment_methods, group_members, friend_groups, contacts, users CASCADE;

CREATE TABLE users (
  user_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_first_name  text NOT NULL,
  user_last_name   text NOT NULL,
  phone            text
);

-- Each user also has one contact row for themselves (same name and phone),
-- so the payer can be a participant and be assigned items like everyone else.
CREATE TABLE contacts (
  contact_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cont_first_name  text NOT NULL,
  cont_last_name   text NOT NULL DEFAULT '',
  phone            text,
  user_id          integer NOT NULL REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE friend_groups (
  group_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name  text NOT NULL
);

CREATE TABLE group_members (
  group_id    integer NOT NULL REFERENCES friend_groups(group_id) ON DELETE CASCADE,
  contact_id  integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, contact_id)
);

CREATE TABLE payment_methods (
  pay_method_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pay_method_name  text NOT NULL UNIQUE
);

CREATE TABLE contacts_payment_method (
  contact_id           integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  pay_method_id        integer NOT NULL REFERENCES payment_methods(pay_method_id),
  pay_method_username  text NOT NULL,
  is_preferred         boolean NOT NULL DEFAULT false,
  PRIMARY KEY (contact_id, pay_method_id)
);
-- At most one preferred payment method per contact.
CREATE UNIQUE INDEX one_preferred_method_per_contact ON contacts_payment_method (contact_id) WHERE is_preferred;

CREATE TABLE events (
  event_id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name  text NOT NULL
);

CREATE TABLE receipts (
  receipt_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id        integer NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  payer_user_id   integer NOT NULL REFERENCES users(user_id),
  merchant_name   text NOT NULL,
  receipt_date    date NOT NULL DEFAULT current_date,
  tax_cents       integer NOT NULL DEFAULT 0 CHECK (tax_cents >= 0),
  fees_cents      integer NOT NULL DEFAULT 0 CHECK (fees_cents >= 0),
  tip_percent     numeric(5,2) NOT NULL DEFAULT 0 CHECK (tip_percent >= 0),
  tip_cents       integer NOT NULL DEFAULT 0 CHECK (tip_cents >= 0),
  total_cents     integer NOT NULL CHECK (total_cents >= 0)  -- total printed on the receipt (items + tax + fees, before tip)
);

CREATE TABLE line_items (
  item_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id   integer NOT NULL REFERENCES receipts(receipt_id) ON DELETE CASCADE,
  description  text NOT NULL,
  price_cents  integer NOT NULL CHECK (price_cents >= 0),
  position     integer NOT NULL
);

-- paid_method_id is empty until the person pays you back; then it records how they paid.
CREATE TABLE participants (
  contact_id      integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  event_id        integer NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
  paid_method_id  integer REFERENCES payment_methods(pay_method_id),
  PRIMARY KEY (contact_id, event_id)
);

CREATE TABLE item_assignments (
  contact_id   integer NOT NULL REFERENCES contacts(contact_id) ON DELETE CASCADE,
  item_id      integer NOT NULL REFERENCES line_items(item_id) ON DELETE CASCADE,
  share_cents  integer NOT NULL CHECK (share_cents >= 0),
  PRIMARY KEY (contact_id, item_id)
);

-- Row Level Security. The app has no login yet and uses Supabase's public "anon" key,
-- so: anyone with the key can READ every table, and can UPDATE only participants.paid_method_id
-- (the "Mark as paid" button). Every other change has to be made from the Supabase dashboard.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','contacts','friend_groups','group_members','payment_methods',
    'contacts_payment_method','events','receipts','line_items','participants','item_assignments']
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY "Public read" ON %I FOR SELECT TO anon USING (true)', t);
  END LOOP;
END $$;

CREATE POLICY "Public can mark paid" ON participants FOR UPDATE TO anon USING (true) WITH CHECK (true);
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM anon;
GRANT UPDATE (paid_method_id) ON participants TO anon;
